spotlight:
  default_visibility: hide

  categories:
    kpi:
      label: Company KPI
      color: blue

    marketing:
      label: Marketing
      color: red

    sales:
      label: Sales
      color: green

    leads:
      label: Leads
      color: orange

    geography:
      label: Geography
      color: pink

    revenue:
      label: Revenue
      color: green

    customers:
      label: Customers
      color: blue

    employees:
      label: Employees
      color: orange

    offices:
      label: Offices
      color: blue

    expansion:
      label: Expansion
      color: pink

    market:
      label: Market
      color: yellow

    growth:
      label: Growth
      color: green

    deals:
      label: Deals
      color: orange

    spain:
      label: Spain
      color: yellow

parameters:
  deal_value_toggle:
    label: "High Value Deal Toggle"
    description: "Filter deals by the amount to see high value deals only"
    options:
          - 500
          - 1000
          - 1500
    default: 1000
    multiple: false