spotlight:
  default_visibility: hide

  categories:
    kpi:
      label: Company KPI
      color: blue

    marketing:
      label: Marketing
      color: red

    sales:
      label: Sales
      color: green

    leads:
      label: Leads
      color: orange

    geography:
      label: Geography
      color: pink

parameters:
  deal_value_toggle:
    label: "High Value Deal Toggle"
    description: "Filter deals by the amount to see high value deals only"
    options:
          - 500
          - 1000
          - 1500
    default: 1000
    multiple: false

  account_segment_toggle:
    label: "Account Segment"
    description: "Select which account segment to display in the dynamic segment metric"
    options:
      - all
      - SMB
      - Midmarket
      - Enterprise
    default: all